export enum Categoria {
    CATARATA = 'CATARATA',
    CIRURGIA_REFRATIVA = 'CIRURGIA_REFRATIVA',
    CORNEA_CONJUNTIVA_E_ESCLERA = 'CORNEA_CONJUNTIVA_E_ESCLERA',
    ESTRABISMO_E_OFTALMOPEATRIA = 'ESTRABISMO_E_OFTALMOPEATRIA',
    FARMACOLOGIA = 'FARMACOLOGIA',
    GLAUCOMA = 'GLAUCOMA',
    LENTES_DE_CONTATO = 'LENTES_DE_CONTATO',
    OPTICA_REFRAOMETRIA_E_VISAO_SUBNORMAL = 'OPTICA_REFRAOMETRIA_E_VISAO_SUBNORMAL',
    PLASTICA_E_ORBITA = 'PLASTICA_E_ORBITA',
    RETINA = 'RETINA',
    UVEITE_E_ONCOLOGIA_OCULAR = 'UVEITE_E_ONCOLOGIA_OCULAR',
}