export enum Plano {
    MENSAL = 'ASSINATURA_MENSAL',
    SEMESTRAL = 'ASSINATURA_SEMESTRAL',
    SEMESTRAL_PARCELADO = '',
    ANUAL = 'ASSINATURA_ANUAL',
    ANUAL_PARCELADO = '',
    PROFESSOR = 'ASSINATURA_PROFESSOR'

}