export enum Plano {
    MENSAL = 'ASSINATURA_MENSAL',
    SEMESTRAL = 'ASSINATURA_SEMESTRAL',
    SEMESTRAL_PARCELADO = 'ASSINATURA_SEMESTRAL_PARCELADA',
    ANUAL = 'ASSINATURA_ANUAL',
    ANUAL_PARCELADO = 'ASSINATURA_ANUAL_PARCELADA',
    PROFESSOR = 'ASSINATURA_PROFESSOR'

}