export enum TipoUsuario {
    RESIDENTE_R1 = 'RESIDENTE_R1',
    RESIDENTE_R2 = 'RESIDENTE_R2',
    RESIDENTE_R3 = 'RESIDENTE_R3',
    ESTUDANTE_MEDICINA = 'ESTUDANTE_MEDICINA',
    OFTALMOLOGISTA = 'OFTALMOLOGISTA',
}   