export enum Relevancia {
    RELEVANCIA_1 = 'RELEVANCIA_1',
    RELEVANCIA_2 = 'RELEVANCIA_2',
    RELEVANCIA_3 = 'RELEVANCIA_3',
    RELEVANCIA_4 = 'RELEVANCIA_4',
    RELEVANCIA_5 = 'RELEVANCIA_5',
    RELEVANCIA_6 = 'RELEVANCIA_6',
    RELEVANCIA_7 = 'RELEVANCIA_7',
    RELEVANCIA_8 = 'RELEVANCIA_8',
    RELEVANCIA_9 = 'RELEVANCIA_9',
    RELEVANCIA_10 = 'RELEVANCIA_10'
}
  