import { Subtema } from "./subtema"; 

export const SubtemaDescricoes: Record<Subtema, string> = {
  [Subtema.BASES_DE_CORNEA]: 'Bases de Córnea',
  [Subtema.OUTRAS_DOENCAS_DA_CONJUNTIVA]: 'Outras Doenças da Conjuntiva',
  [Subtema.OUTRAS_CERATITES]: 'Outras Ceratites',
  [Subtema.ECTASIAS_CORNEANAS]: 'Ectasias Corneanas',
  [Subtema.DEGENERACOES_CORNEANAS]: 'Degenerações Corneanas',
  [Subtema.SINDROMES_FOLICULARES]: 'Síndromes Foliculares',
  [Subtema.ESCLERITES_E_EPISCLERITES]: 'Esclerites e Episclerites',
  [Subtema.BANCO_DE_OLHOS_E_TRANSPLANTES_DE_CORNEA]: 'Banco de Olhos e Transplantes de Córnea',
  [Subtema.CERATITE_HERPETICA_E_HZO]: 'Ceratite Herpética e HZO',
  [Subtema.ALERGIA_OCULAR]: 'Alergia Ocular',
  [Subtema.DISTROFIAS_DO_ESTROMA_CORNEANO]: 'Distrofias do Estroma Corneano',
  [Subtema.TRANSPLANTES_LAMELARES]: 'Transplantes Lamelares',
  [Subtema.CERATITES_BACTERIANAS]: 'Ceratites Bacterianas',
  [Subtema.CERATITES_FUNGICAS_E_ACANTHAMOEBA]: 'Ceratites Fúngicas e Acanthamoeba',
  [Subtema.DISTROFIAS_DO_EPITELIO_CORNEANO]: 'Distrofias do Epitélio Corneano',
  [Subtema.BASES_DE_CONJUNTIVA_LIMBO_E_TENON]: 'Bases de Conjuntiva, Limbo e Tenon',
  [Subtema.BASES_DE_ESCLERA]: 'Bases de Esclera',
  [Subtema.PUK_E_MOOREN]: 'PUK e Mooren',
  [Subtema.DISTROFIAS_DO_ENDOTELIO_CORNEANO]: 'Distrofias do Endotélio Corneano',
  [Subtema.OUTRAS_DOENCAS_DA_CORNEA]: 'Outras Doenças da Córnea',
  [Subtema.TRAUMA_DE_CORNEA]: 'Trauma de Córnea',
  [Subtema.BASES_RETINA]: 'Bases Retina',
  [Subtema.EXAMES_DE_IMAGEM]: 'Exames de Imagem',
  [Subtema.RETINOPATIA_DIABETICA]: 'Retinopatia Diabética',
  [Subtema.DESCOLAMENTO_DE_RETINA]: 'Descolamento de Retina',
  [Subtema.DMRI]: 'DMRI',
  [Subtema.OCLUSOES_VASCULARES]: 'Oclusões Vasculares',
  [Subtema.OUTRAS_DOENCAS_VASCULARES]: 'Outras Doenças Vasculares',
  [Subtema.DOENCAS_DA_INTERFACE_VITREORRETINIANA]: 'Doenças da Interface Vitreorretiniana',
  [Subtema.ESTUDOS_ELETROFISIOLOGICOS]: 'Estudos Eletrofisiológicos',
  [Subtema.VVPP_IE_E_PNEUMATICA]: 'VVPP, IE e Pneumática',
  [Subtema.DISTROFIAS_DIFUSAS_DA_RETINA_E_DA_COROIDE]: 'Distrofias Difusas da Retina e da Coroide',
  [Subtema.BASES_VITREO]: 'Bases Vítreo',
  [Subtema.CORIORRETINOPATIA_SEROSA_CENTRAL]: 'Coriorretinopatia Serosa Central',
  [Subtema.RETINOPATIA_FALCIFORME]: 'Retinopatia Falciforme',
  [Subtema.MIOPIA_PATOLOGICA_E_ESTRIAS_ANGIOIDES]: 'Miopia Patológica e Estrias Angioides',
  [Subtema.DISTROFIAS_MACULARES]: 'Distrofias Maculares',
  [Subtema.RETINOPATIA_HIPERTENSIVA]: 'Retinopatia Hipertensiva',
  [Subtema.RETINOPATIA_DA_PREMATURIDADE]: 'Retinopatia da Prematuridade',
  [Subtema.TRAUMA_DE_RETINA_E_COROIDE]: 'Trauma de Retina e Coroide',
  [Subtema.ENDOFTALMITE]: 'Endoftalmite',
  [Subtema.OPACIDADES_VITREAS]: 'Opacidades Vítreas',
  [Subtema.ANOMALIAS_CONGENITAS]: 'Anomalias Congênitas',
  [Subtema.OUTRAS_PATOLOGIAS_DE_RETINA]: 'Outras Patologias de Retina',
  [Subtema.OUTROS_GLAUCOMAS_SECUNDARIOS]: 'Outros Glaucomas Secundários',
  [Subtema.GLAUCOMA_BASES]: 'Glaucoma Bases',
  [Subtema.TRABECULECTOMIA]: 'Trabeculectomia',
  [Subtema.CAMPO_VISUAL]: 'Campo Visual',
  [Subtema.GPAA_HO_E_GPN]: 'GPAA, HO e GPN',
  [Subtema.TERAPIA_MEDICAMENTOSA]: 'Terapia Medicamentosa',
  [Subtema.GL_PIGMENTAR_E_GL_PSEUDOEXFOLIATIVO]: 'GL. Pigmentar e GL. Pseudoexfoliativo',
  [Subtema.GLAUCOMA_DE_ANGULO_FECHADO]: 'Glaucoma de Ângulo Fechado',
  [Subtema.GLAUCOMA_CONGENITO_PRIMARIO]: 'Glaucoma Congênito Primário',
  [Subtema.NEUROCRISTOPATIAS]: 'Neurocristopatias',
  [Subtema.TERAPIA_LASER_DO_GLAUCOMA]: 'Terapia Laser do Glaucoma',
  [Subtema.GLAUCOMA_NEOVASCULAR]: 'Glaucoma Neovascular',
  [Subtema.ICE_SYNDROME]: 'ICE Syndrome',
  [Subtema.GLAUCOMA_POS_TRABECULAR]: 'Glaucoma Pós-Trabecular',
  [Subtema.IMPLANTE_DE_TUBO]: 'Implante de Tubo',
  [Subtema.GDX_HRT_E_OCT]: 'GDx, HRT e OCT',
  [Subtema.COMPLICACOES_PERIOPERATORIAS_E_POS_OPERATORIAS]: 'Complicações Perioperatórias e Pós-operatórias',
  [Subtema.PRE_OPERATORIO_VISCOELASTICOS_E_ANESTESIA]: 'Pré-operatório, Viscoelásticos e Anestesia',
  [Subtema.ALTERACOES_CONGENITAS_DO_CRISTALINO]: 'Alterações Congênitas do Cristalino',
  [Subtema.BASES_DO_CRISTALINO]: 'Bases do Cristalino',
  [Subtema.FATORES_DE_RISCO_E_CATARATAS_ESPECIAIS]: 'Fatores de Risco e Cataratas Especiais',
  [Subtema.FLUIDICA_E_APARELHO_DE_FACOEMULSIFICACAO]: 'Fluídica e Aparelho de Facoemulsificação',
  [Subtema.LENTES_INTRAOCULARES]: 'Lentes Intraoculares',
  [Subtema.TECNICA_CIRURGICA]: 'Técnica Cirúrgica',
  [Subtema.AFECCOES_DAS_VIAS_DE_DRENAGEM]: 'Afecções das Vias de Drenagem',
  [Subtema.BASES_DE_SISTEMA_LACRIMAL]: 'Bases de Sistema Lacrimal',
  [Subtema.BASES_DE_PLASTICA_OCULAR]: 'Bases de Plástica Ocular',
  [Subtema.PTOSE_DA_PALPEBRA_E_DO_SUPERCILIO]: 'Ptose da Pálpebra e do Supercílio',
  [Subtema.DOENCAS_DOS_CILIOS_E_INFLAMATORIAS_DAS_PALPEBRAS]: 'Doenças dos Cílios e Inflamatórias das Pálpebras',
  [Subtema.TUMORES_PALPEBRAIS]: 'Tumores Palpebrais',
  [Subtema.PROPEDEUTICA_DAS_VIAS_DE_DRENAGEM]: 'Propedêutica das Vias de Drenagem',
  [Subtema.ANOMALIAS_CONGENITAS_PALPEBRAIS]: 'Anomalias Congênitas Palpebrais',
  [Subtema.ENTROPIO]: 'Entrópio',
  [Subtema.ECTROPIO]: 'Ectrópio',
  [Subtema.TRAUMA_E_RECONSTRUCAO_PALPEBRAL]: 'Trauma e Reconstrução Palpebral',
  [Subtema.SINDROME_DE_SJOGREN]: 'Síndrome de Sjögren',
  [Subtema.BLEFAROPLASTIA]: 'Blefaroplastia',
  [Subtema.SINDROME_DAS_PALPEBRAS_FROUXAS]: 'Síndrome das Pálpebras Frouxas',
  [Subtema.UVEITE_POR_TOXOPLASMOSE_SIFILIS_E_TUBERCULOSE]: 'Uveíte por Toxoplasmose, Sífilis e Tuberculose',
  [Subtema.UVEITES_VIRAIS]: 'Uveítes Virais',
  [Subtema.COROIDITES_NAO_INFECCIOSAS]: 'Coroidites Não Infecciosas',
  [Subtema.OUTRAS_UVEITES_ANTERIORES]: 'Outras Uveítes Anteriores',
  [Subtema.BASES_DE_COROIDE]: 'Bases de Coroide',
  [Subtema.UVEITES_NAS_ESPONDILOARTROPATIAS]: 'Uveítes nas Espondiloartropatias',
  [Subtema.VOGT_KOYANAGI_HARADA_E_OFTALMIA_SIMPATICA]: 'Vogt-Koyanagi-Harada e Oftalmia Simpática',
  [Subtema.BEHCET_E_SARCOIDOSE]: 'Behçet e Sarcoidose',
  [Subtema.BASES_DE_IRIS]: 'Bases de Íris',
  [Subtema.BASES_DE_CORPO_CILIAR]: 'Bases de Corpo Ciliar',
  [Subtema.UVEITE_INTERMEDIARIA]: 'Uveíte Intermediária',
  [Subtema.TOXOCARIASE_OCULAR_E_DUSN]: 'Toxocaríase Ocular e DUSN',
  [Subtema.UVEITE_NA_ARTRITE_IDIOPATICA_JUVENIL]: 'Uveíte na Artrite Idiopática Juvenil',
  [Subtema.ANATOMIA_DAS_VIAS_OPTICAS]: 'Anatomia das Vias Ópticas',
  [Subtema.III_IV_E_VI_PARES_CRANIANOS]: 'III, IV e VI Pares Cranianos',
  [Subtema.SINDROMES_PUPILARES]: 'Síndromes Pupilares',
  [Subtema.NEURITES_OPTICAS]: 'Neurites Ópticas',
  [Subtema.PAPILEDEMA_E_PSEUDOTUMOR_CEREBRAL]: 'Papiledema e Pseudotumor Cerebral',
  [Subtema.MIOPATIAS_OCULARES]: 'Miopatias Oculares',
  [Subtema.NEUROPATIAS_OPTICAS_ISQUEMICAS]: 'Neuropatias Ópticas Isquêmicas',
  [Subtema.NEUROPATIAS_TOXICAS_E_CARENCIAIS]: 'Neuropatias Tóxicas e Carenciais',
  [Subtema.NISTAGMOS]: 'Nistagmos',
  [Subtema.NEUROPATIAS_OPTICAS_HEREDITARIAS]: 'Neuropatias Ópticas Hereditárias',
  [Subtema.BASES_DE_ESTRABISMO]: 'Bases de Estrabismo',
  [Subtema.AMBLIOPIA]: 'Ambliopia',
  [Subtema.NOCOES_CIRURGICAS]: 'Noções Cirúrgicas',
  [Subtema.DESVIOS_VERTICAIS_E_ALFABETICOS]: 'Desvios Verticais e Alfabéticos',
  [Subtema.SINDROMES_ESPECIAIS]: 'Síndromes Especiais',
  [Subtema.ESOTROPIAS]: 'Esotropias',
  [Subtema.EXOTROPIAS]: 'Exotropias',
  [Subtema.PROPEDEUTICA_SENSORIAL]: 'Propedêutica Sensorial',
  [Subtema.PROPEDEUTICA_MOTORA]: 'Propedêutica Motora',
  [Subtema.ADAPTACOES_MOTORAS_E_SENSORIAIS]: 'Adaptações Motoras e Sensoriais',
  [Subtema.ASTIGMATISMO]: 'Astigmatismo',
  [Subtema.ACOMODACAO]: 'Acomodação',
  [Subtema.REFRACAO]: 'Refração',
  [Subtema.ACUIDADE_VISUAL]: 'Acuidade Visual',
  [Subtema.PONTO_PROXIMO_E_PONTO_REMOTO]: 'Ponto Próximo e Ponto Remoto',
  [Subtema.RETINOSCOPIA]: 'Retinoscopia',
  [Subtema.EQUIVALENTE_ESFERICO]: 'Equivalente Esférico',
  [Subtema.MATERIAL_DAS_LENTES]: 'Material das Lentes',
  [Subtema.MIOPIA]: 'Miopia',
  [Subtema.OCULOS_BIFOCAIS_E_MULTIFOCAIS]: 'Óculos Bifocais e Multifocais',
  [Subtema.HIPERMETROPIA]: 'Hipermetropia',
  [Subtema.ANISOMETROPIA]: 'Anisometropia',
  [Subtema.CAUSAS_DE_INSATISFACAO_COM_OS_OCULOS]: 'Causas de Insatisfação com os Óculos',
  [Subtema.TRANSPOSICAO_DE_LENTES]: 'Transposição de Lentes',
  [Subtema.TRATAMENTO_DAS_LENTES]: 'Tratamento das Lentes',
  [Subtema.LENTES_E_ESPELHOS]: 'Lentes e Espelhos',
  [Subtema.PRISMAS]: 'Prismas',
  [Subtema.INTERACAO_DA_LUZ_COM_A_SUPERFICIE_DOS_MATERIAIS]: 'Interação da Luz com a Superfície dos Materiais',
  [Subtema.PROPRIEDADES_DA_LUZ]: 'Propriedades da Luz',
  [Subtema.OPTICA]: 'Óptica',
  [Subtema.INTERACAO_DA_LUZ_COM_ARESTAS_E_ORIFICIOS]: 'Interação da Luz com Arestas e Orifícios',
  [Subtema.VERGENCIA_OBJETO_E_IMAGEM]: 'Vergência, Objeto e Imagem',
  [Subtema.ABERRACOES_OPTICAS]: 'Aberrações Ópticas',
  [Subtema.ANTIBIOTICOS_ANTIFUNGICOS_E_ANTIVIRAIS]: 'Antibióticos, Antifúngicos e Antivirais',
  [Subtema.HIPOTENSORES_OCULARES]: 'Hipotensores Oculares',
  [Subtema.CICLOPLEGICOS_E_MIDRIATICOS]: 'Cicloplégicos e Midriáticos',
  [Subtema.PILOCARPINA_E_CARBACOL]: 'Pilocarpina e Carbacol',
  [Subtema.CONCEITOS_GERAIS]: 'Conceitos Gerais',
  [Subtema.ANESTESICOS]: 'Anestésicos',
  [Subtema.CORTICOIDES_E_AINES]: 'Corticoides e AINEs',
  [Subtema.CLOROQUINA]: 'Cloroquina',
  [Subtema.CORANTES_VITAIS]: 'Corantes Vitais',
  [Subtema.CONSERVANTES]: 'Conservantes',
  [Subtema.ANTI_VEGF]: 'Anti-VEGF',
  [Subtema.COSMIATRIA]: 'Cosmiatria',
  [Subtema.AINES]: 'AINEs',
  [Subtema.MITOMICINA_C_E_5_FLUORACIL]: 'Mitomicina C e 5-Fluoracil',
  [Subtema.MELANOMA_DE_COROIDE]: 'Melanoma de Coroide',
  [Subtema.TUMORES_EPIBULBARES_MALIGNOS]: 'Tumores Epibulbares Malignos',
  [Subtema.RETINOBLASTOMA]: 'Retinoblastoma',
  [Subtema.LESOES_PIGMENTADAS_DA_SUPERFICIE_OCULAR]: 'Lesões Pigmentadas da Superfície Ocular',
  [Subtema.FACOMATOSES]: 'Facomatoses',
  [Subtema.TUMORES_EPIBULBARES_BENIGNOS]: 'Tumores Epibulbares Benignos',
  [Subtema.OUTROS_TUMORES_INTRAOCULARES]: 'Outros Tumores Intraoculares',
  [Subtema.CIRURGIA_REFRATIVA]: 'Cirurgia Refrativa',
  [Subtema.LENTES_DE_CONTATO]: 'Lentes de Contato',
  [Subtema.VISAO_SUBNORMAL]: 'Visão Subnormal',
  [Subtema.GENETICA_OCULAR]: 'Genética Ocular',
  [Subtema.EMBRIOLOGIA]: 'Embriologia',
  [Subtema.PATOLOGIA_OCULAR]: 'Patologia Ocular',
  [Subtema.ETICA_MEDICA]: 'Ética Médica',
  [Subtema.ESTUDOS_CIENTIFICOS]: 'Estudos Científicos',
  [Subtema.SENSIBILIDADE_E_ESPECIFICIDADE]: 'Sensibilidade e Especificidade',
  [Subtema.PSF]: 'PSF',
  [Subtema.SAUDE_PUBLICA]: 'Saúde Pública',
  [Subtema.ADMINISTRACAO_HOSPITALAR]: 'Administração Hospitalar',
  [Subtema.NAO_CLASSIFICADA]: 'Não classificada',
  [Subtema.OUTROS]: 'Outros',
};