import { Subtema } from "./subtema"; 

export const SubtemaDescricoes: Record<Subtema, string> = {
  [Subtema.BASES_DE_CORNEA]: 'Bases de Córnea',
  [Subtema.OUTRAS_DOENCAS_DA_CONJUNTIVA]: 'Outras Doenças da Conjuntiva',
  [Subtema.OUTRAS_CERATITES]: 'Outras Ceratites',
  [Subtema.ECTASIAS_CORNEANAS]: 'Ectasias Corneanas',
  [Subtema.DEGENERACOES_CORNEANAS]: 'Degenerações Corneanas',
  [Subtema.SINDROMES_FOLICULARES]: 'Síndromes Foliculares',
  [Subtema.ESCLERITES_E_EPISCLERITES]: 'Esclerites e Episclerites',
  [Subtema.BANCO_DE_OLHOS_E_TRANSPLANTES_DE_CORNEA]: 'Banco de Olhos e Transplantes de Córnea',
  [Subtema.CERATITE_HERPETICA_E_HZO]: 'Ceratite Herpética e HZO',
  [Subtema.ALERGIA_OCULAR]: 'Alergia Ocular',
  [Subtema.DISTROFIAS_DO_ESTROMA_CORNEANO]: 'Distrofias do Estroma Corneano',
  [Subtema.TRANSPLANTES_LAMELARES]: 'Transplantes Lamelares',
  [Subtema.CERATITES_BACTERIANAS]: 'Ceratites Bacterianas',
  [Subtema.CERATITES_FUNGICAS_E_ACANTHAMOEBA]: 'Ceratites Fúngicas e Acanthamoeba',
  [Subtema.DISTROFIAS_DO_EPITELIO_CORNEANO]: 'Distrofias do Epitélio Corneano',
  [Subtema.BASES_DE_CONJUNTIVA_LIMBO_E_TENON]: 'Bases de Conjuntiva, Limbo e Tenon',
  [Subtema.BASES_DE_ESCLERA]: 'Bases de Esclera',
  [Subtema.PUK_E_MOOREN]: 'PUK e Mooren',
  [Subtema.DISTROFIAS_DO_ENDOTELIO_CORNEANO]: 'Distrofias do Endotélio Corneano',
  [Subtema.OUTRAS_DOENCAS_DA_CORNEA]: 'Outras Doenças da Córnea',
  [Subtema.TRAUMA_DE_CORNEA]: 'Trauma de Córnea',
  [Subtema.BASES_RETINA]: 'Bases Retina',
  [Subtema.EXAMES_DE_IMAGEM]: 'Exames de Imagem',
  [Subtema.RETINOPATIA_DIABETICA]: 'Retinopatia Diabética',
  [Subtema.DESCOLAMENTO_DE_RETINA]: 'Descolamento de Retina',
  [Subtema.DMRI]: 'DMRI',
  [Subtema.OCLUSOES_VASCULARES]: 'Oclusões Vasculares',
  [Subtema.OUTRAS_DOENCAS_VASCULARES]: 'Outras Doenças Vasculares',
  [Subtema.DOENCAS_DA_INTERFACE_VITREORRETINIANA]: 'Doenças da Interface Vitreorretiniana',
  [Subtema.ESTUDOS_ELETROFISIOLOGICOS]: 'Estudos Eletrofisiológicos',
  [Subtema.VVPP_IE_E_PNEUMATICA]: 'VVPP, IE e Pneumática',
  [Subtema.DISTROFIAS_DIFUSAS_DA_RETINA_E_DA_COROIDE]: 'Distrofias Difusas da Retina e da Coroide',
  [Subtema.BASES_VITREO]: 'Bases Vítreo',
  [Subtema.CORIORRETINOPATIA_SEROSA_CENTRAL]: 'Coriorretinopatia Serosa Central',
  [Subtema.RETINOPATIA_FALCIFORME]: 'Retinopatia Falciforme',
  [Subtema.MIOPIA_PATOLOGICA_E_ESTRIAS_ANGIOIDES]: 'Miopia Patológica e Estrias Angioides',
  [Subtema.DISTROFIAS_MACULARES]: 'Distrofias Maculares',
  [Subtema.RETINOPATIA_HIPERTENSIVA]: 'Retinopatia Hipertensiva',
  [Subtema.RETINOPATIA_DA_PREMATURIDADE]: 'Retinopatia da Prematuridade',
  [Subtema.TRAUMA_DE_RETINA_E_COROIDE]: 'Trauma de Retina e Coroide',
  [Subtema.ENDOFTALMITE]: 'Endoftalmite',
  [Subtema.OPACIDADES_VITREAS]: 'Opacidades Vítreas',
  [Subtema.ANOMALIAS_CONGENITAS]: 'Anomalias Congênitas',
  [Subtema.OUTRAS_PATOLOGIAS_DE_RETINA]: 'Outras Patologias de Retina',
  [Subtema.OUTROS_GLAUCOMAS_SECUNDARIOS]: 'Outros Glaucomas Secundários',
  [Subtema.GLAUCOMA_BASES]: 'Glaucoma Bases',
  [Subtema.TRABECULECTOMIA]: 'Trabeculectomia',
  [Subtema.CAMPO_VISUAL]: 'Campo Visual',
  [Subtema.GPAA_HO_E_GPN]: 'GPAA, HO e GPN',
  [Subtema.TERAPIA_MEDICAMENTOSA]: 'Terapia Medicamentosa',
  [Subtema.GL_PIGMENTAR_E_GL_PSEUDOEXFOLIATIVO]: 'GL. Pigmentar e GL. Pseudoexfoliativo',
  [Subtema.GLAUCOMA_DE_ANGULO_FECHADO]: 'Glaucoma de Ângulo Fechado',
  [Subtema.GLAUCOMA_CONGENITO_PRIMARIO]: 'Glaucoma Congênito Primário',
  [Subtema.NEUROCRISTOPATIAS]: 'Neurocristopatias',
  [Subtema.TERAPIA_LASER_DO_GLAUCOMA]: 'Terapia Laser do Glaucoma',
  [Subtema.GLAUCOMA_NEOVASCULAR]: 'Glaucoma Neovascular',
  [Subtema.ICE_SYNDROME]: 'ICE Syndrome',
  [Subtema.GLAUCOMA_POS_TRABECULAR]: 'Glaucoma Pós-Trabecular',
  [Subtema.IMPLANTE_DE_TUBO]: 'Implante de Tubo',
  [Subtema.GDX_HRT_E_OCT]: 'GDx, HRT e OCT',
  [Subtema.COMPLICACOES_PERIOPERATORIAS_E_POS_OPERATORIAS]: 'Complicações Perioperatórias e Pós-operatórias',
  [Subtema.PRE_OPERATORIO_VISCOELASTICOS_E_ANESTESIA]: 'Pré-operatório, Viscoelásticos e Anestesia',
  [Subtema.ALTERACOES_CONGENITAS_DO_CRISTALINO]: 'Alterações Congênitas do Cristalino',
  [Subtema.BASES_DO_CRISTALINO]: 'Bases do Cristalino',
  [Subtema.FATORES_DE_RISCO_E_CATARATAS_ESPECIAIS]: 'Fatores de Risco e Cataratas Especiais',
  [Subtema.FLUIDICA_E_APARELHO_DE_FACOEMULSIFICACAO]: 'Fluídica e Aparelho de Facoemulsificação',
  [Subtema.LENTES_INTRAOCULARES]: 'Lentes Intraoculares',
  [Subtema.TECNICA_CIRURGICA]: 'Técnica Cirúrgica',
};