import { Tema } from "./tema";

export const TemaDescricoes: Record<Tema, string> = {
  [Tema.CATARATA]: 'Catarata',
  [Tema.CIRURGIA_REFRATIVA]: 'Cirurgia Refrativa',
  [Tema.CORNEA_CONJUNTIVA_E_ESCLERA]: 'Córnea, Conjuntiva e Esclera',
  [Tema.CRISTALINO]: 'Cristalino',
  [Tema.EMBRIOLOGIA]: 'Embriologia',
  [Tema.ESTRABISMO]: 'Estrabismo',
  [Tema.FARMACOLOGIA]: 'Farmacologia',
  [Tema.GENETICA_OCULAR]: 'Genética Ocular',
  [Tema.GLAUCOMA]: 'Glaucoma',
  [Tema.LENTES_DE_CONTATO]: 'Lentes de Contato',
  [Tema.NAO_CLASSIFICADA]: 'Não classificada',
  [Tema.NEUROFTALMOLOGIA]: 'Neuroftalmologia',
  [Tema.OPTICA]: 'Óptica',
  [Tema.OUTROS]: 'Outros',
  [Tema.ORBITA]: 'Órbita',
  [Tema.PATOLOGIA_OCULAR]: 'Patologia Ocular',
  [Tema.PLASTICA_OCULAR_E_SISTEMA_LACRIMAL]: 'Plástica Ocular e Sistema Lacrimal',
  [Tema.REFRACAO]: 'Refração',
  [Tema.RETINA]: 'Retina',
  [Tema.TUMORES_INTRAOCULARES]: 'Tumores Intraoculares',
  [Tema.UVEITE]: 'Uveíte',
  [Tema.VISAO_SUBNORMAL]: 'Visão Subnormal',
};