export enum Tema {
    OFTALMOLOGIA_GERAL = 'OFTALMOLOGIA_GERAL',
    CIRURGIA_OCULAR = 'CIRURGIA_OCULAR',
    LENTES_DE_CONTATO = 'LENTES_DE_CONTATO',
    DOENCAS_OCULARES = 'DOENCAS_OCULARES',
  }
  